# Generated by Django 5.0.6 on 2024-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('ciudad', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveBigIntegerField()),
                ('ocupacion', models.CharField(choices=[('Emp', 'Empleado'), ('Inde', 'Independiente'), ('Pen', 'Pensionado')], default='Emp', max_length=20)),
            ],
        ),
    ]
