# Generated by Django 5.0.6 on 2024-05-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='fecha',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='documento',
            new_name='numero_de_documento',
        ),
    ]
