# Generated by Django 5.0.6 on 2024-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_rename_fecha_personas_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_de_documento',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
