# Generated by Django 5.0.6 on 2024-05-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_personas_numero_de_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='personas',
            name='ocupacion',
            field=models.CharField(choices=[('Emp', 'Empleado'), ('Inde', 'Independiente'), ('Pen', 'Pensionado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personas',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.ciudad'),
        ),
    ]
