# Generated by Django 5.0.6 on 2024-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_ciudad_alter_personas_ocupacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_de_documento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
