# Generated by Django 5.0.6 on 2024-05-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_personas_numero_de_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
    ]
