# Generated by Django 4.2.13 on 2024-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_delete_ciudad_rename_apellido_personas_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='viable',
            field=models.BooleanField(default=False),
        ),
    ]
