# Generated by Django 4.2.13 on 2024-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_personas_viable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='viable',
            field=models.CharField(choices=[('viable', 'Viable'), ('No_viable', 'No viable')], default='', max_length=20),
        ),
    ]
