# Generated by Django 5.0.6 on 2024-06-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_personas_viable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='viable',
        ),
    ]
