# Generated by Django 5.0.6 on 2024-06-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_remove_personas_viable'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='viable',
            field=models.CharField(choices=[('viable', 'viable'), ('No_viable', 'viable')], default='', max_length=20),
        ),
    ]
